name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: set perm for Gradle
        run: chmod +x gradlew    
      - name: Build with Gradle
        run: ./gradlew build

      - name: List Target Directory
        run: |
          cd build
          ls -la
        
      - name: List Target Dir
        run: |
          cd build/libs
          ls -la
          
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - name: Run Pipeline Scanner
        run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "1a1f33f23cf2b4c518bf57de261ca3bd" --veracode_api_key "a2e94d5e020dbf64e5ef5f1e9d0f190de18f6356d16e62ead70d3d5ff095f39fc6237bddd286ca35548c4434367f7ac00a7e738ec353567ab42f255866a93014" --file "build/libs/gradle-github-actions-example.jar" --fail_on_severity="Very High, High"
