name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: set permisssion for Gradle
        run: chmod +x gradlew    
      - name: Build with Gradle
        run: ./gradlew build
      - name: List Target Directory
        run: |
          cd target
          ls -la
        
        