name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: set permisssion for Gradle
        run: chmod +x gradlew    
      - name: Build with Gradle
        run: ./gradlew build

      - name: List Target Directory
        run: |
          cd build
          ls -la
        
      - name: List Target Directory
        run: |
          cd build/libs
          ls -la
          
      - run: java -jar pipeline-scan.jar --veracode_api_id "ab44f6d1c4d03efadb40c17ffc4aed95" --veracode_api_key "0b1ac08ef1e493f601065291c57c648aefbca329b74496f9056ca89ec9de533d51a9107ac8297e748daecb14f713a9d37fc71b152873dd57c67d9d8727892363" --fail_on_severity="Very High, High" --file veracode-pipeline-scan-results-to-sarif.zip
        continue-on-error: true
      - name: Convert pipeline scan output to SARIF format 
        id: convert
        uses: ./
        with:
          pipeline-results-json: results.json
          
      - name: Veracode Static Analysis Pipeline Scan and SARIF import
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-pipeline-scan-results-to-sarif@c4e3ac33a116df4b7074d53747d8814e8fdf974b
        uses: veracode/veracode-pipeline-scan-results-to-sarif@v0.1.5
        with:
    # location of the pipeline json result file
            pipeline-results-json: results.json
    # the path to the SARIF file as an output of the transformation
            output-results-sarif: veracode-results.sarif
    # a path prefix conversion before publish in the SARIF file
            source-base-path-1: "build/libs/gradle-github-actions-example.jar"
    # The conversion rule of Veracode findings to GitHub level
            finding-rule-level: default is 4:3:0

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'CRS-DEMO-APP'
          createprofile: false
          filepath: 'build/libs/*.jar'
          vid: '1a1f33f23cf2b4c518bf57de261ca3bd'
          vkey: 'a2e94d5e020dbf64e5ef5f1e9d0f190de18f6356d16e62ead70d3d5ff095f39fc6237bddd286ca35548c4434367f7ac00a7e738ec353567ab42f255866a93014'
